/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StandardsRouteImport } from './routes/standards'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RiskLibraryRouteImport } from './routes/risk-library'
import { Route as QueueRouteImport } from './routes/queue'
import { Route as LiteratureRouteImport } from './routes/literature'
import { Route as IndexRouteImport } from './routes/index'

const StandardsRoute = StandardsRouteImport.update({
  id: '/standards',
  path: '/standards',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RiskLibraryRoute = RiskLibraryRouteImport.update({
  id: '/risk-library',
  path: '/risk-library',
  getParentRoute: () => rootRouteImport,
} as any)
const QueueRoute = QueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => rootRouteImport,
} as any)
const LiteratureRoute = LiteratureRouteImport.update({
  id: '/literature',
  path: '/literature',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/literature': typeof LiteratureRoute
  '/queue': typeof QueueRoute
  '/risk-library': typeof RiskLibraryRoute
  '/settings': typeof SettingsRoute
  '/standards': typeof StandardsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/literature': typeof LiteratureRoute
  '/queue': typeof QueueRoute
  '/risk-library': typeof RiskLibraryRoute
  '/settings': typeof SettingsRoute
  '/standards': typeof StandardsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/literature': typeof LiteratureRoute
  '/queue': typeof QueueRoute
  '/risk-library': typeof RiskLibraryRoute
  '/settings': typeof SettingsRoute
  '/standards': typeof StandardsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/literature'
    | '/queue'
    | '/risk-library'
    | '/settings'
    | '/standards'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/literature'
    | '/queue'
    | '/risk-library'
    | '/settings'
    | '/standards'
  id:
    | '__root__'
    | '/'
    | '/literature'
    | '/queue'
    | '/risk-library'
    | '/settings'
    | '/standards'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LiteratureRoute: typeof LiteratureRoute
  QueueRoute: typeof QueueRoute
  RiskLibraryRoute: typeof RiskLibraryRoute
  SettingsRoute: typeof SettingsRoute
  StandardsRoute: typeof StandardsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/standards': {
      id: '/standards'
      path: '/standards'
      fullPath: '/standards'
      preLoaderRoute: typeof StandardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risk-library': {
      id: '/risk-library'
      path: '/risk-library'
      fullPath: '/risk-library'
      preLoaderRoute: typeof RiskLibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/queue': {
      id: '/queue'
      path: '/queue'
      fullPath: '/queue'
      preLoaderRoute: typeof QueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/literature': {
      id: '/literature'
      path: '/literature'
      fullPath: '/literature'
      preLoaderRoute: typeof LiteratureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LiteratureRoute: LiteratureRoute,
  QueueRoute: QueueRoute,
  RiskLibraryRoute: RiskLibraryRoute,
  SettingsRoute: SettingsRoute,
  StandardsRoute: StandardsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
